<!DOCTYPE html>
<html>

<style>
    .pagebreak {
        page-break-before: always;
    }

    pre code {
        background-color: #eee;
        border: 1px solid #999;
        display: block;
        padding: 20px;
    }

    .toc-list li > a > .page {
        min-width: 2ch;
        font-variant-numeric: tabular-nums;
        text-align: right;
    }

</style>

<head>
    <title>{{ title }}</title>
</head>

<div class="pagebreak"> </div>  /* Page Break */

<body>
/* Table of Contents */
    <ol class="toc-list" role="list">
    <li>
        <a href="#link_to_heading">
        <span class="title">Chapter or subsection title</span>
        <span class="page"><span class="visually-hidden">Page</span> 1</span>
        </a>

        <ol role="list">
        <!-- subsection items -->
        </ol>
    </li>
    </ol>

<div class="pagebreak"> </div>  /* Page Break */


</body>
</html>